version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build: ./frontend/onlinecompiler
    ports:
      - "3000:80"
    depends_on:
      - backend
